---

# Delegate further configuration to subtasks
# placed in this same directory.

- include: install.yml
- include: configure.yml
  when: not rethinkdb_is_proxy_node

# Flush handlers now, so we avoid starting the process and then
# restarting it immediately after notifications are flushed.
- meta: flush_handlers

- name: Ensure RethinkDB is running
  become: yes
  when: not rethinkdb_is_proxy_node
  service:
    name: "{{ rethinkdb_service_name }}"
    state: running
  tags:
    - init
    - rethinkdb
- include: proxy-node.yml
  when: rethinkdb_is_proxy_node
