- name: Create upstart service
  sudo: yes
  template:
    src: rethinkdb-proxy.conf
    dest: "/etc/init/rethinkdb-proxy.conf"
    owner: "{{rethinkdb_user}}"
    group: "{{rethinkdb_group}}"
  tags:
    - rethinkdb-proxy

- name: Ensure RethinkDB-proxy is running
  sudo: yes
  service:
    name: "rethinkdb-proxy"
    state: restarted
  tags:
    - rethinkdb-proxy

